### ISSUE TITLE
Working colisionhook

### ISSUE THREAD

**Issue by daffyyyy** [JustZerooo/Signatures#1]
Working colisionhook, from this repo it doesn't work
![image](https://user-images.githubusercontent.com/41084667/216724197-19755b1c-fedb-421b-9cae-a0939e34d6e7.png)
Colisionhook ext and gamedata
[colisionhook.zip](https://github.com/JustZerooo/Signatures/files/10583276/colisionhook.zip)

ext source - https://github.com/Adrianilloo/Collisionhook

**Comment by JustZerooo** [comment]
Added in : 4f6a8ad95f8725811792dc49e917fc5b1d9284f9
